### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'slugify'

### ISSUE THREAD

**Issue by daslicht** [ChristopherDosin/Shopware-6-Blog-Plugin#155]
Is that a know issue?:
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'slugify' in '/Users/tester/Sites/shopware/custom/plugins/SasBlogModule/src/Resources/app/administration/src/module/blog-module/page/sas-blog-detail'
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/lib/Compilation.js:925:10
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/neo-async/async.js:2830:7
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/neo-async/async.js:6877:13
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:43:1)
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/enhanced-resolve/lib/forEachBail.js:30:14
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/enhanced-resolve/lib/ModulesInHierachicDirectoriesPlugin.js:56:16
    at /Users/tester/Sites/shopware/vendor/shopware/administration/Resources/app/administration/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
resolve 'slugify' in '/Users/tester/Sites/shopware/custom/plugins/SasBlogModule/src/Resources/app/administration/src/module/blog-module/page/sas-blog-detail'
  Parsed request is a module
  using description file: /Users/tester/Sites/shopware/custom/plugins/SasBlogModule/src/Resources/app/administration/package.json (relative path: ./src/module/blog-module/page/sas-blog-detail)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/tester/Sites/shopware/custom/plugins/SasBlogModule/src/Resources/app/administration/src/module/blog-module/page/sas-blog-detail/node_modules doesn't exist or is not a directory
      /Users/tester/Sites/shopware/custom/plugins/SasBlogModule/src/Resources/app/administration/src/module/blog-module/page/node_modules doesn't exist or is not a directory
      /Users/tester/Sites/shopware/custom/plugins/SasBlogModule/src/Resources/app/administration/src/module/blog-module/node_modules doesn't exist or is not a directory
      /Users/tester/Sites/shopware/custom/plugins/SasBlogModule/src/Resources/app/administration/src/module/node_modules doesn't exist or is not a directory
      /Users/tester/Sites/shopware/custom/plugins/SasBlogModule/src/Resources/app/administration/src/node_modules doesn't exist or is not a directory
      /Users/tester/Sites/shopware/custom/plugins/SasBlogModule/src/Resources/app/administration/node_modules doesn't exist or is not a directory
      /Users/tester/Sites/shopware/custom/plugins/SasBlogModule/src/Resources/app/node_modules doesn't exist or is not a directory
      /Users/tester/Sites/shopware/custom/plugins/SasBlogModule/src/Resources/node_modules doesn't exist or is not a directory
      /Users/tester/Sites/shopware/custom/plugins/SasBlogModule/src/node_modules doesn't exist or is not a directory
      /Users/tester/Sites/shopware/custom/plugins/SasBlogModule/node_modules doesn't exist or is not a directory
      /Users/tester/Sites/shopware/custom/plugins/node_modules doesn't exist or is not a directory
      /Users/tester/Sites/shopware/custom/node_modules doesn't exist or is not a directory
      /Users/tester/Sites/shopware/node_modules doesn't exist or is not a directory
      /Users/tester/Sites/node_modules doesn't exist or is not a directory
      /Users/tester/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

```

**Comment by daslicht** [comment]
manually installing it seams to work, but should npm install not run automatically after install ?

**Comment by ChristopherDosin** [comment]
@daslicht Did you installed the plugin from the repository?
If so, yes: You have to execute `npm install` within `src/Resources/app/administration` since there're no compiled files within a GitHub repository.

**Comment by daslicht** [comment]
I installed it from within shopify
